/* Autogenerated by png2wx.pl on Mon Dec 16 19:05:53 2019 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_active;
extern wxBitmap *_img_inactive;
extern wxBitmap *_img_toggled;

#endif /* ICONS_H */
