/* Autogenerated by png2wx.pl on Fri Dec 20 16:54:26 2019 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_active;
extern wxBitmap *_img_inactive;
extern wxBitmap *_img_toggled;
extern wxBitmap *_img_activewpt;
extern wxBitmap *_img_targetwpt;
extern wxBitmap *_img_VMG;
extern wxBitmap *_img_SOG;

#endif /* ICONS_H */
